export { default as HomePage } from '@/pages/Home/Home.jsx'
export { default as AdminPage } from '@/pages/Admin/Admin.jsx'
export { default as ContactPage } from '@/pages/Contact/Contact.jsx'
export { default as AboutUsPage } from '@/pages/AboutUs/AboutUs.jsx'
export { default as ProductPage } from '@/pages/Product/Product.jsx'
export { default as ProductDetailPage } from '@/pages/ProductDetail/ProductDetail.jsx'
export { default as CartPage } from '@/pages/Cart/Cart.jsx'
export { default as OrderPage } from '@/pages/Order/Order.jsx'