export { default as CarouselBg } from "./CarouselBg/CarouselBg.jsx"
export { default as Introduce } from "./Introduce/Introduce.jsx"
export { default as Discover } from "./Discover/Discover.jsx"
export { default as TimeService } from "./TimeService/TimeService.jsx"
export { default as ImgShop } from "./ImgShop/ImgShop.jsx"
export { default as Comment } from "./Comment/Comment.jsx"